### ISSUE TITLE
Providers or plugins? Providers

### ISSUE THREAD

**Issue by alexcouper** [pretenders/deploystream#8]
@txels:

Which do we want to call them?

We currently have a package called providers and we call them plugins pretty much everywhere else...

**Comment by txels** [comment]
I realise I had only replied to this in an already closed PR. For the record:

I prefer `providers` for code that implements a given service, and `plugins` for add-on (possibly 3rd party) components that can potentially be installed dynamically (e.g. the way you can implement Jenkins plugins).

A plugin may implement one or more providers (e.g. a Github/Bitbucket plugin may implement some source control features plus some planning features - via its support for issues, plus some team information provider, if we ever support that...).

Since I think it is too early to get into implementing some sort of dynamic plugin system, we may want to use `provider` exclusively for now, if you agree with my definitions.
